name: TopLeaderboards
version: 1.0.0
main: TopLeaderboards\Main
api: 5.0.0
author: ZyberPE

commands:
  lb:
    description: Leaderboard commands
    usage: "/lb spawn <name> | /lb remove <name> | /lb list"
    permission: topleaderboards.admin

permissions:
  topleaderboards.admin:
    default: op
