name: TopLeaderboards
main: TopLeaderboards\Main
version: 1.0.0
api: 5.0.0
author: ZyberPE

commands:
  lb:
    description: Leaderboard commands
    usage: "/lb spawn <name> | /lb remove <name> | /lb list"
    permission: topleaderboards.command

permissions:
  topleaderboards.command:
    default: op
